### PR TITLE
[GH-170] Fix CI Hydra issue

### PR DESCRIPTION
**Pull request by ksaric**
https://github.com/input-output-hk/cardano-shell/issues/170

Fix the failing CI and remove unnecessary Nix derivations.

### CODE REVIEW

**Comment by ksaric** [comment]
It would be nice if somebody reviewed https://github.com/input-output-hk/cardano-shell/pull/167 so we can merge that, rebase this and then merge this to fix all CI issues popping up:
- https://github.com/input-output-hk/cardano-shell/pull/167
- https://github.com/input-output-hk/cardano-shell/pull/168
- https://github.com/input-output-hk/cardano-shell/pull/148

**Comment by jbgi** [comment]
`runCoveralls` is not needed anymore? (can be removed from `default.nix` then?)

**Comment by ksaric** [comment]
@jbgi Good point, I'll put that back.

**Comment by ksaric** [comment]
Added `ci/hydra:Cardano:cardano-shell:required` branch protection. Thanks @jbgi.

**Comment by ksaric** [comment]
Why isn't Coveralls working? :thinking: 
Do we need to add it to the CI pipeline? And if so, won't that void the Hydra caches when building it?

Otherwise, I have no clue why it's not working.

**Comment by ksaric** [comment]
We can leave the coveralls issue for another task, not urgent.

**Comment by 365andreas** [comment]
@ksaric  Seems that https://github.com/input-output-hk/cardano-shell/commit/30829cc82ed74fd9da8d8be79b77da4b36a728d4#diff-8b496edab86012a437e80897eb7129c0 removed coverage checking.

**Comment by ksaric** [comment]
@365andreas Yep, I noticed that. Adding it here results in:
```
building '/nix/store/s3lka8z0wrivjvrvdzqb2x9a44lgim0d-stack-hpc-coveralls-0.0.4.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/61jvs7n897lrnb2d60mpl84js8jwi7if-ghc-8.4.3.
ignoring (possibly broken) abi-depends field for packages
unpacking sources
unpacking source archive /nix/store/7b3im8mq46vjdfy44lpimll7smhj4gfl-stack-hpc-coveralls-0.0.4.0.tar.gz
source root is stack-hpc-coveralls-0.0.4.0
setting SOURCE_DATE_EPOCH to timestamp 1465994082 of file stack-hpc-coveralls-0.0.4.0/stack.yaml
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/build/setup-package.conf.d -j12 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/6mfjg609dql1kvzsp68m72y8pg93wgp0-stack-hpc-coveralls-0.0.4.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/79bk76ifsrcdzndfraqak4j28r90zxsi-stack-hpc-coveralls-0.0.4.0-doc/share/doc/stack-hpc-coveralls-0.0.4.0 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-option=-j12 --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --enable-library-vanilla --enable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/1nmw74s77li7qswbmbln0c74gln13i6w-ncurses-6.1/lib --extra-lib-dirs=/nix/store/kn55ah0qwa4gyr5nncjdagrwbq9s4n2p-gmp-6.1.2/lib
Using Parsec parser
Configuring stack-hpc-coveralls-0.0.4.0...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:958:20 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:462:12 in Cabal-2.2.0.1:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:609:20 in Cabal-2.2.0.1:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:67:5 in Cabal-2.2.0.1:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:191:19 in Cabal-2.2.0.1:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:119:27 in Cabal-2.2.0.1:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing dependencies:
hlint ==1.*

builder for '/nix/store/s3lka8z0wrivjvrvdzqb2x9a44lgim0d-stack-hpc-coveralls-0.0.4.0.drv' failed with exit code 1
error: build of '/nix/store/s3lka8z0wrivjvrvdzqb2x9a44lgim0d-stack-hpc-coveralls-0.0.4.0.drv' failed
```

**Pull request merged**
